des: des.ml
	ocamlfind ocamlc -package hex -linkpkg -g -o des des.ml

aes: aes.ml
	ocamlfind ocamlc -package hex -linkpkg -g -o aes aes.ml

rc4: rc4.ml
	ocamlfind ocamlc -package hex -linkpkg -g -o rc4 rc4.ml

clean:
	rm *.cm* des aes rc4
